server:
  port: ${server_port:8081}
  
# json日期时间格式化
spring:
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss       #日期格式化
    serialization:
      write-dates-as-timestamps: false
    
#mybatis-plus
mybatis-plus:
  mapper-locations: classpath*:**/mapper/**/*.xml,classpath*:**/dao/**/*.xml
  #实体扫描，多个package用逗号或者分号分隔
  type-aliases-package: com.transcend.plm.configcenter.**.infrastructure.repository.po
  type-enums-package: com.transcend.plm.configcenter.common.enums
  global-config:
    db-config:
      id-type: ASSIGN_UUID   #AUTO
      table-prefix: 
      logic-delete-field: deleteFlag
      logic-delete-value: 1
      logic-not-delete-value: 0
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl #开启sql日志
    #database-id: 0
  extends:
    page-limit: 500
    overflow: false
    auto-routing: false
    meta-object-handler: true
    meta-props:
      create-time: createdTime  #createTime
      create-user: createdBy    #createUser
      update-time: updatedTime  #updateTime
      update-user: updatedBy    #updateUser
      
tr:
  exception:
    print:
      enabled: true
            